#!/usr/bin/python
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# copyright 2011 Mario Frasca

if __name__ == '__main__':
    import sys
    from os import path
    sys.path.append(path.dirname(path.dirname(__file__)))

    from datetime import datetime
    import argparse, uuid

    parser = argparse.ArgumentParser(description='convert text files to epub document.')
    parser.add_argument('destination', type=str,
                        help='the name of the epub document')
    parser.add_argument('sources', type=str, nargs='+',
                        help='the text files to include in the epub')
    parser.add_argument('--keep-line-breaks', action='store_true', default=True)
    parser.add_argument('--type')
    parser.add_argument('--title')
    parser.add_argument('--creator')
    parser.add_argument('--description')
    parser.add_argument('--publisher')
    parser.add_argument('--date', default=datetime.date(datetime.today()))
    parser.add_argument('--language')
    parser.add_argument('--identifier', default=str(uuid.uuid4()).replace('-', ''))

    args = parser.parse_args()

    from txt2epublib import main
    main(**vars(args))
